### ISSUE TITLE
Not able to scan project properly

### ISSUE THREAD

**Issue by myaddressline** [AppSecDev/appscan-source-gradle-plugin#8]
Hi,

I am using appscan with gradle. it scan project successfully but generate blank report .ppf file not generate for all subfolders. Also checked in logs it scan only a single subfolders and scan 0 files so report is also blank. Please let me know what configuration need to change so that it generate all .ppf files and generate a valid report

**Comment by mattmurp** [comment]
Hi,

Please ensure that you execute "gradle :runScan" (note the : character preceding the task name).

If that doesn't help, can you provide the verbose gradle output?

- Matt

**Comment by myaddressline** [comment]
Hi,
I also try with :runScan But got same result. I have four folders in my application. But ppf file is generate for only a single folder also it scan 0 files for that folder also.


**Console output is :** 
:createProject
:folder1:createProject
:folder2:createProject
:folder3:createProject
:folder4:compileJava UP-TO-DATE
:folder4:createProject
[ounceCreateProject] CRWSA3005I Exporting IBM Security AppScan Source project to /folder4/folder4.ppf
[ounceCreateProject] CRWSA3010I Exporting IBM Security AppScan Source application to /appscan/appscan.paf

:createCLIScript
:folder1:createCLIScript
:folder2:createCLIScript
:folder3:createCLIScript
:folder4:createCLIScript

:runScan
[ounceCli] CRWSA3020I Executing CLI script /appscan/cliscript.txt
[ounceCli] CRWSA3015I Output sent to /appscan/appscanlog.txt

and the output for appscanlog.txt is 

>> Welcome to IBM Security AppScan Source!
Login successful.
New scan started
Scanning with Scan Configuration: Quick scan
Scanning with cross-project analysis disabled
Scanning Project folder4( 1 of 1 )

Preparing project for scan...
Preparing project for scan...
Scanned project folder4: Total files: 0 Total findings: 0 Total lines: 0 vkloc: 0.000000 v-density: 0.000000
Scanned application applicationName : Total files: 0 Total findings: 0 Total lines: 0 vkloc: 0.000000 v-density: 0.000000
Scan completed: Total files: 0 Total findings: 0 Total lines: 0 vkloc: 0.000000 v-density: 0.000000
Elapsed Time - 0 Hour(s) 0 Minute(s) 5 Second(s)
                -------------------
                Total Call Sites: 0
                Total Definitive Security Findings with High Severity: 0
                Total Definitive Security Findings with Medium Severity: 0
                Total Definitive Security Findings with Low Severity: 0
                Total Suspect Security Findings with High Severity: 0
                Total Suspect Security Findings with Medium Severity: 0
                Total Suspect Security Findings with Low Severity: 0
                Total Scan Coverage Findings with High Severity: 0
                Total Scan Coverage Findings with Medium Severity: 0
                Total Scan Coverage Findings with Low Severity: 0
                Total Lines: 0
                Max V-Density: 0
                Max V/kloc: 0
                V-Density: 0
                V/kloc: 0
Logged out.
>> Exiting the IBM Security AppScan Source Command Line Interface...
>> Exiting the IBM Security AppScan Source Command Line Interface...

**Comment by mattmurp** [comment]
Hi,

The plugin only creates AppScan Source projects (.ppf files) for Java projects.  Are folder1, folder2, and folder3 Java projects?

The folder4 project is clearly Java, but it seems that no files are found in the project.  Does folder4 contain any java source files?  Can you show the contents of that project directory?

If this is just a sample project, can you attach it?

**Comment by myaddressline** [comment]
Hi Matt,
Yes all folders are java projects. and all folders have java source files.

**Comment by mattmurp** [comment]
Hi,
Is this still a problem?  If so, can you provide the sample project you're testing against?
Thanks.

**Comment by mattmurp** [comment]
Closing the issue since there hasn't been a response.
