### ISSUE TITLE
Recognizing Java/War plugin by plugins.hasPlugin("org.gradle.java")

### ISSUE THREAD

**Issue by hmozaffari** [AppSecDev/appscan-source-gradle-plugin#9]
In older versions of Gradle plugins are not recognized by fully qualified names like ```plugins.hasPlugin("org.gradle.java")``` and they are recognized by id like ```plugins.hasPlugin("java")```. It would be nice to change the condition to ```project.plugins.hasPlugin("org.gradle.java") || project.plugins.hasPlugin("java")``` across the code to be backward compatible:
```Java
For example:
project.task('createProject',
   description: "Generates an AppScan Source project for this Gradle project.",
   type: com.ibm.appscan.gradle.tasks.AppScanCreateProject) {
   classfiles = {project.plugins.hasPlugin("org.gradle.java") && project.hasProperty("compileJava") ? project.compileJava.outputs.files : project.files(project.projectDir)}
```

**Comment by mattmurp** [comment]
This makes sense, although newer versions of gradle will accept either format.
Please create a pull request following the instructions in Contributing.md.

**Comment by mattmurp** [comment]
This is in version 1.1.7.
